### ISSUE TITLE
NoSuchMethodError on org.slf4j.Logger.atDebug()

### ISSUE THREAD

**Issue by mboullouz** [SandroHc/reactive-jikan#8]
I'm playing with this **great** 🥇  library inside Spring Boot (Java 17) web app, 
but for unknown reason I get this exception :  
`java.lang.NoSuchMethodError: 'org.slf4j.spi.LoggingEventBuilder org.slf4j.Logger.atDebug()'`
I'm using maven latest version : `1.0.2`
My intuition is that maven is picking the wrong version of self4j but I'm not familiar with maven exclusions strategies  on Pom lavel
Any hint on how to solve this ?

**Comment by SandroHc** [comment]
The issue you're facing is happening because the dependency [spring-boot-starter-logging](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-logging/2.6.3) comes with its own version of [slf4j-api](https://mvnrepository.com/artifact/org.slf4j/slf4j-api) (currently 1.7.32), whereas this library uses an experimental version (2.0.0-alpha1).

Using an experimental version of a dependency on a published library is never a good idea, so I'll migrate to the latest stable version.

I'll release version 1.1.0 in a few hours to fix this issue.

**Comment by SandroHc** [comment]
Version [1.1.0](https://repo.maven.apache.org/maven2/net/sandrohc/reactive-jikan/) has been released. 🎉

Can you upgrade to this version and confirm that your issue is fixed?

**Comment by mboullouz** [comment]
Thank you very much @SandroHc , great job 👍 
One last thing, is it possible to support search for users : `https://api.jikan.moe/v4/users` ?
Currently we are using RestTemplate but it's very ugly and lacks Typesafety  
_(I'm open to a small $ contribution, let me know if you have paypal or something similar)_

**Comment by SandroHc** [comment]
Thank you for confirming the fix, I'll close this issue now.

As for your other request, the endpoint [getUsersSearch](https://docs.api.jikan.moe/#operation/getUsersSearch) is only available on V4 of the Jikan API, but unfortunately this library only supports V3. I have created #9 to track the migration to V4.

**Comment by SandroHc** [comment]
Just read your edit. Although your gesture is greatly appreciated, it would be more beneficial to support the maintainers of the Jikan API directly - https://patreon.com/jikan. They're the ones doing the bulk of the work and the ones with the server/infrastructure costs! 😁
